//This file is generated by vargen. Please, do not modify it.
package template

var (
	Golang = "//{{- /*gotype: github.com/mtreload/VariablesGenerator/cmd/vargen.Templa*/ -}}\n{{ .Meta.Message }}\npackage {{ .Package }}\n\nvar (\n{{range .Variables}}\n    {{ .Name }} = \"{{.Value}}\"\n{{end}}\n)"
)
